### ISSUE TITLE
Implement admin album resource

### ISSUE THREAD

**Issue by yummta** [codeableorg/rails-youtube-music-clon#10]
- [ ] GET     admin/albums(.:format)          with tests
- [ ] POST    admin/albums(.:format)          with tests
- [ ] GET     admin/albums/new(.:format)      with tests
- [ ] GET     admin/albums/:id/edit(.:format) with tests
- [ ] GET     admin/albums/:id(.:format)      with tests
- [ ] PATCH   admin/albums/:id(.:format)      with tests
- [ ] PUT     admin/albums/:id(.:format)      with tests
- [ ] DELETE  admin/albums/:id(.:format)      with tests

**Comment by yummta** [comment]
The tests are missing

**Comment by test0n3** [comment]
tests for /admin namespace are not required.
