### ISSUE TITLE
Create routes API

### ISSUE THREAD

**Issue by yummta** [codeableorg/rails-youtube-music-clon#3]
```
GET: api/songs
GET: api/songs/:id
GET: api/songs/:id/artist
GET: api/songs/:id/album
GET: api/artist
GET: api/artist/:id
GET: api/artist/:id/songs
GET: api/artist/:id/albums
GET: api/albums
GET: api/albums/:id/artist
GET: api/albums/:id/songs
GET: api/artist/search
GET: api/songs/search
GET: api/album/search
PATCH: api/songs/:id/progress
PATCH: api/songs/:id/rating
PATCH: api/album/:id/rating
```

**Comment by test0n3** [comment]
`GET: api/songs
GET: api/songs/:id
GET: api/songs/:id/artists
GET: api/songs/:id/albums
GET: api/artists
GET: api/artists/:id
GET: api/artists/:id/songs
GET: api/artists/:id/albums
GET: api/albums
GET: api/albums/:id
GET: api/albums/:id/artist
GET: api/albums/:id/songs
GET: api/artists/search
GET: api/songs/search
GET: api/albums/search
PATCH: api/songs/:id/progress
PATCH: api/songs/:id/rating
PATCH: api/albums/:id/rating`
